generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      TransactionDescription
    theme:            default
    css:             /sf/sf_admin/css/admin_main.css
    list:
      title:            Transaction Description List
      display:        [id,title,transaction_type]
    edit:
      title:          Transaction Description
      display:        [id,title,transaction_type_id]
      
      actions:
        _list: ~
        _save: ~
        _save_and_add: ~
    create:
      title:          Add Transaction Description